services:
  - type: web
    name: car-rental-app
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node dist/app.js
    envVars:
      - key: MONGODB_URI
        sync: false # You will set this manually in Render dashboard
      - key: JWT_SECRET
        sync: false # You will set this manually in Render dashboard
